web/models/Caracteristica.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "caracteristica".
 *
 * @property int $id
 * @property int $construccion_id
 * @property string $nombre
 * @property string $descripcion
 * @property string $updated_at
 * @property string $created_at
 *
 * @property Construccion $construccion
 */
class Caracteristica extends \yii\db\ActiveRecord
{
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'caracteristica';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['construccion_id', 'nombre', 'descripcion'], 'required'],
            [['construccion_id'], 'integer'],
            [['updated_at', 'created_at'], 'safe'],
            [['nombre'], 'string', 'max' => 100],
            [['descripcion'], 'string', 'max' => 500],
            [['construccion_id'], 'exist', 'skipOnError' => true, 'targetClass' => Construccion::className(), 'targetAttribute' => ['construccion_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'construccion_id' => 'Construccion ID',
            'nombre' => 'Nombre de la caracteristica',
            'descripcion' => 'Descripcion',
            'updated_at' => 'Ultima actualización',
            'created_at' => 'Creado',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConstruccion()
    {
        return $this->hasOne(Construccion::className(), ['id' => 'construccion_id']);
    }
}

web/controllers/CaracteristicaController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\Caracteristica;
use app\models\Construccion;
use app\models\CaracteristicaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CaracteristicaController implements the CRUD actions for Caracteristica model.
 */
class CaracteristicaController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['delete',"update","create"],
                'rules' => [
                    [
                        'actions' => ['delete',"update","create"],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Caracteristica models.
     * @return mixed
     */
    public function actionIndex($idConstruccion = 0)
    {
        if(isset($idConstruccion))
        {
            $searchModel = new CaracteristicaSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $dataProvider->query->andWhere('construccion_id = '.$idConstruccion);
            $construccion = Construccion::findOne($idConstruccion);
        }
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            "construccion" => $construccion
        ]);
        
    }

    /**
     * Displays a single Caracteristica model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Caracteristica model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($idConstruccion = null)
    {
        
        $model = new Caracteristica();
        $construccion = Construccion::findOne($idConstruccion);
        $model->construccion_id = $idConstruccion;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            "construccion" => $construccion
        ]);
    }

    /**
     * Updates an existing Caracteristica model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
       ]);
    }

    /**
     * Deletes an existing Caracteristica model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $this->findModel($id)->delete();

        return $this->redirect(['index',"idConstruccion"=>$model->construccion_id]);
    }

    /**
     * Finds the Caracteristica model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Caracteristica the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Caracteristica::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

web/controllers/ConstruccionController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use isudakoff\authclient\FoursquareApi;
use app\models\Construccion;
use app\models\Galeria;
use app\models\ConstruccionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ConstruccionController implements the CRUD actions for Construccion model.
 */
class ConstruccionController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['delete',"update","create"],
                'rules' => [
                    [
                        'actions' => ['delete',"update","create"],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Construccion models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ConstruccionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        foreach ($dataProvider->getModels() as &$data)
        {
            $c = "";
            foreach($data->caracteristicas as $caract )
                $c = $c . $caract->nombre . "<br />";
            if($c === "")
                $c = "No hay caracteristicas";
            $data->caracteristicasTexto = $c;
            
            $g = "";
            foreach($data->galerias as $gal )
                $g = $g . $gal->nombre . "<br />";
            if($g === "")
                $g = "No hay ubicaciones";
            $data->galeriasTexto = $g;
        }
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

     /**
     * Lists all Construccion models en un mapa.
     * @return mixed
     */
    public function actionMaps()
    {
        
        $dataProvider = Construccion::find()->indexBy('id')->all();
        
        return $this->render('maps', [
            
            'dataProvider' => $dataProvider,
        ]);
    }
    

    /**
     * Displays a single Construccion model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Construccion model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Construccion();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->registrarLugaresCercanos($model->id);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model

        ]);
    }

    /**
     * Updates an existing Construccion model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Construccion model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Construccion model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Construccion the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Construccion::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('La página requerida no existe.');
    }
    
    protected function registrarLugaresCercanos($idConstruccion)
    {
            $construccion = Construccion::findOne($idConstruccion);

            // Set your client key and secret
            $client_key = "FKLUBMKUFN5F4EXYEUFBQS4AMESPXXPRTC3W2WQACSJGNJSU";
            $client_secret = "QOZ35KDDACSV31CPT4X324JVHSY1GUWROC5PYWEDUDKUTZY1";
            // Load the Foursquare API library
                if($client_key=="" or $client_secret=="")
                {
                    echo 'Load client key and client secret from <a href="https://developer.foursquare.com/">foursquare</a>';
                    exit;
                }
            $foursquare = new FoursquareApi($client_key,$client_secret);
                //$location = array_key_exists("location",$_GET) ? $_GET['location'] : "Montreal, QC";
                //list($lat,$lng) = $foursquare->GeoLocate($location);
            // Prepare parameters
            $lat= $construccion->latitud;
            $lng = $construccion->longitud;
            $params = array("ll"=>"$lat,$lng");
            // Perform a request to a public resource
            $response = $foursquare->GetPublic("venues/search",$params);
            //$response = $foursquare->GetPublic("venues/4b034dbff964a520744e22e3/photos");
            $venues = $foursquare->getResponseFromJsonString($response);
            //$venues = json_decode($response);

        $listaLugares = array();
        foreach($venues as $key => $r)
        {
            for($i = 0; $i < count($r); $i++)
            {
                $arregloLugares = (array)$r[$i];
                $reg = array();
                foreach($arregloLugares as $key => $datos)
                {     
                    switch($key)
                    {
                        case "id":
                        case "name":
                            $reg[$key]=$datos;
                            break;
                        case "location":
                           $ubicacionCompleta = (array)$datos;
                            foreach($ubicacionCompleta as $k => $ubicacion)
                            {
                                switch($k)
                                {
                                    case "address":
                                    case "lat":
                                    case "lng":
                                        $reg[$k]=$ubicacion;
                                        break;
                                }
                            }
                        break;
                    }

                }
                $listaLugares[] = $reg;

            }
        }
        //Sacaremos las fotos
        //Ya teniendo los lugares ingresaremos los primeros 5
        $contador = 0;
        
        foreach($listaLugares as &$lugar)    
        {
            $model = new Galeria();
            foreach($lugar as $key => $valor)
            {
               switch($key)
                {
                   case "id":
                       //echo $valor . "    ";
                       /* $response = $foursquare->GetPublic("venues/".$valor."/photos");
                        print_r($response);
                        $fotos = $foursquare->getResponseFromJsonString($response);
                        print_r($fotos);
                        exit;
                        */
                        //$lugar["fotos"] = $fotos;
                       break;
                   case "name":
                       $model->nombre = "".$valor;
                       break;
                   case "lat":
                       $model->latitud = "".$valor;
                       break;
                   case "lng":
                       $model->longitud = "".$valor;
                       break;
                }
            }
            //IMAGEN GENERICA DEBIDO A QUE NOS REESTRINGIO ESA PARTE FOURSQUARE
            //Por que, Foursquare me indico cuota excedida con el siguiente error
            //{"meta":{"code":429,"errorType":"quota_exceeded","errorDetail":"Quota exceeded","requestId":"5b863c34dd57972c545faacb"},
            //"response":{}}stdClass Object ( )
                $model->ruta = "http://www.mexlead.com.mx/imagenes/construccion.jpg";
                $model->construccion_id = $construccion->id;
                
                if ($model->save()) {
                    Yii::debug("Alta de lugar cercano " . $model->nombre);
                }else
                {
                    $errores = $model->errors;
                    print_r($errores);
                    exit;
                }
            if($contador >= 4)
                break;
            $contador++;
        }
    }
}

web/views/caracteristica/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Caracteristica */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="caracteristica-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'construccion_id')->hiddenInput(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'descripcion')->textInput(['maxlength' => true]) ?>

    <!--?= $form->field($model, 'updated_at')->textInput() ?-->

    <!--?= $form->field($model, 'created_at')->textInput() ?-->

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

web/views/caracteristica/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CaracteristicaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="caracteristica-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'construccion_id') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'descripcion') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Resetear', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

web/views/caracteristica/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Caracteristica */

$this->title = 'Agregar Caracteristica a la construcción ' . Html::encode($construccion->nombre);
$this->params['breadcrumbs'][] = ['label' => 'Construcciones', 'url' => ['/construccion/index']];
$this->params['breadcrumbs'][] = ['label' => $construccion->nombre, 'url' => ['/construccion/view', 'id' => $construccion->id]];
$this->params['breadcrumbs'][] = ['label' => 'Caracteristicas', 'url' => ['index',"idConstruccion"=>$construccion->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="caracteristica-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

web/views/caracteristica/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CaracteristicaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Caracteristicas de la construcción ' . Html::encode($construccion->nombre);
$this->params['breadcrumbs'][] = ['label' => 'Construcciones', 'url' => ['/construccion/index']];
$this->params['breadcrumbs'][] = ['label' => $construccion->nombre, 'url' => ['/construccion/view', 'id' => $construccion->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="caracteristica-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Agregar Característica', ['create',"idConstruccion"=>$construccion->id], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'construccion_id',
            'nombre',
            'descripcion',
            //'updated_at',
            //'created_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

web/views/caracteristica/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Caracteristica */

$this->title = 'Actualizar Característica: ' . $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Construcciones', 'url' => ['/construccion/index']];
$this->params['breadcrumbs'][] = ['label' => $model->construccion->nombre, 'url' => ['/construccion/view', 'id' => $model->construccion->id]];
$this->params['breadcrumbs'][] = ['label' => 'Caracteristicas', 'url' => ['index',"idConstruccion"=>$model->construccion->id]];
$this->params['breadcrumbs'][] = ['label' => $model->nombre, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="caracteristica-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

web/views/caracteristica/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Caracteristica */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Construcciones', 'url' => ['/construccion/index']];
$this->params['breadcrumbs'][] = ['label' => $model->construccion->nombre, 'url' => ['/construccion/view', 'id' => $model->construccion->id]];
$this->params['breadcrumbs'][] = ['label' => 'Caracteristicas', 'url' => ['index',"idConstruccion"=>$model->construccion->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="caracteristica-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Borrar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Estas seguro de borrar la caracteristica '.$model->nombre.' ?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            //'construccion',
            'nombre',
            'descripcion',
            'updated_at',
            'created_at',
        ],
    ]) ?>

</div>